AllCops:
  Exclude:
    - 'migration/db/*.rb'
    - 'migration/db/migrate/*.rb'
    - 'config/puma/*.rb'
    - 'Gemfile.lock'
    - 'Rakefile'
    - 'api/spec/*'
    - 'core/spec/*'
Style/FrozenStringLiteralComment:
  Enabled: false
Style/Documentation:
  Enabled: false
Lint/AmbiguousBlockAssociation:
  Enabled: false